### PR TITLE
Add comments in do_shm_update

### PR DESCRIPTION
**Pull request by DemiMarie**
This code is incredibly tricky and difficult to understand.  It turns
out to be correct, but checking that took hours, so add some comments to
help anyone else who looks at it.

### CODE REVIEW

**Comment by DemiMarie** [comment]
There were at least two times when reading this code that I thought it had a security vulnerability.  That is how tricky this is.

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by DemiMarie** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Pull request merged**
