### PR TITLE
Add .gitlab-ci.yml

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
PipelineRefresh

**Comment by marmarek** [comment]
@fepitre install fails on centos8:
```
 Problem: conflicting requests
  - nothing provides python38-pydbus needed by qubes-audio-daemon-4.1.11-1.centos8.x86_64
```
Do you care about AudioVM on centos8, or should I exclude it?

**Comment by marmarek** [comment]
@fepitre see above comment - that's the last thing blocking this PR.

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
@marmarek we are good here :)

**Pull request merged**
